### PR TITLE
Fix bugs

### LINKED ISSUE #28: Restarting/spawning too quickly in multiplayer has issues with balls
Either balls' positions don't get tracked properly by the other player, or ball spawning is straight up screwed up in that the just roll out from a fixed position from the floor. To be investigated further. Likely to be something to do with the ball manager

spawningwrongplace

### PR DESCRIPTION
**Pull request by khooroko**
**Description**
Fixes #28 I think. Definitely an improvement in terms of ball management, and there as less visual discrepancies for the balls now.
Also fixed something that I accidentally introduced when improving smacking, which is that tools that are faded still have their colliders being non-trigger (i.e. balls can hit them and bounce off). This fixes that and also makes the fade show similarly on both players' eyes.

@lyhvictoria

**Impact**
- [x] Medium

**Test Plan**
Smack some balls and restart and smack some balls again

### CODE REVIEW

File: Assets/Scripts/BallManager.cs [hunk 1]
```diff
@@ -41,7 +41,7 @@ public class BallManager : MonoBehaviour {
         if (numberOfStartingBalls > ballPool.childCount) {
             AddNewBallsToPool(numberOfStartingBalls - ballPool.childCount);
         }
-
```
Comment (lyhvictoria) [inline Assets/Scripts/BallManager.cs:44]: 👍

**Review by lyhvictoria — APPROVED** [review]
works fine
